const express = require("express")
const app = express()
const authRouter = require("./routes/v1/auth.js")
const userRouter = require("./routes/v1/user.js")
const categoryRouter = require("./routes/v1/category.js")
const courseRouter = require("./routes/v1/course.js")
const sessionRouter = require("./routes/v1/session.js")
const commentrouter = require("./routes/v1/comments.js")
const contactRouter = require("./routes/v1/contact.js")
const newsletterRouter = require("./routes/v1/newsletter.js")
const searchRouter = require("./routes/v1/search.js")
const notificationRouter = require("./routes/v1/notification.js")
const offRouter = require("./routes/v1/off.js")
const orderRouter = require("./routes/v1/order.js")
const ticketRouter = require("./routes/v1/ticket.js")
const departmenRouter = require("./routes/v1/department.js")

const path = require("path")
const multer = require("multer")

app.use(express.json())
app.use(express.static(path.join(__dirname, "public", "course", "cover")))
app.use("/v1/auth", authRouter)
app.use("/v1/user", userRouter)
app.use("/v1/category", categoryRouter)
app.use("/v1/courses", courseRouter)
app.use("/v1/session", sessionRouter)
app.use("/v1/contact", contactRouter)
app.use("/v1/comments", commentrouter)
app.use("/v1/newsletter", newsletterRouter)
app.use("/v1/search", searchRouter)
app.use("/v1/notification", notificationRouter)
app.use("/v1/offer", offRouter)
app.use("/v1/order", orderRouter)
app.use("/v1/ticket", ticketRouter)
app.use("/v1/departmen", departmenRouter)




module.exports = app